### PR TITLE
Lazy require 'typescript' module.

### PR DESCRIPTION
**Pull request by indexzero**
> Regression introduced by #70. 

This is blocking. Currently any fresh install of a pure JavaScript `@oclif` project will die with:

```
Cannot find module 'typescript'
```

1. No stack trace.
2. No helpful message.
3. Zip. Zilch. Zero.

Debugging aside, this is due to the fact that these JavaScript projects have no need to have `typescript` in the `dependencies` or `devDependencies` of their `package.json`. 

**Solution:** since `src/ts-node.js` appears to exist to load TypeScript definitions for plugins and other modules consumed by a given CLI project using `@oclif` we only require `typescript` when we have confirmed that a `tsconfig.json` exists within that directory. 

Not sure the right approach to test this, but hopefully we can land a hotfix and then discuss testability / debuggability separately.

### CODE REVIEW

File: src/ts-node.ts [hunk 1]
```diff
@@ -61,6 +60,8 @@ function registerTSNode(root: string) {
 function loadTSConfig(root: string): TSConfig | undefined {
   const tsconfigPath = path.join(root, 'tsconfig.json')
   if (fs.existsSync(tsconfigPath)) {
+    // Lazy-require 'typescript' to support JavaScript @oclif projects.
+    const {parseConfigFileTextToJson} = require('typescript')
```
Comment (trevor-scheer) [inline src/ts-node.ts]: I think this doesn't solve the root of the issue where `typescript` is currently listed in `devDependencies` instead of `dependencies` in the package file. I suspect this will still break for TS projects.

I'm only here since our project is affected as well, so 🙇 thank you for taking the time to submit a PR!

Comment (indexzero) [reply src/ts-node.ts]: @trevor-scheer yes, that's why I updated 6042e18 to be even lazier about it.

Comment (indexzero) [reply src/ts-node.ts]: Thanks for giving it a look over though, glad to know we're not the only ones getting bitten by it 🙏

Comment (trevor-scheer) [reply src/ts-node.ts]: What I'm suggesting is, now that `typescript` is being required as an actual runtime dependency (no matter how lazily), it needs to be listed in `dependencies` instead of `devDependencies` for this package.

File: src/ts-node.ts [hunk 2]
```diff
@@ -1,7 +1,15 @@
 import * as fs from 'fs'
 import * as path from 'path'
 import * as TSNode from 'ts-node'
-import {parseConfigFileTextToJson} from 'typescript'
+
+let parseConfigFileTextToJson
+try {
+  // Lazy-require 'typescript' to support JavaScript @oclif projects.
+  ({parseConfigFileTextToJson} = require('typescript'))
```
Comment (lsanwick) [inline src/ts-node.ts]: This should probably just be done with dynamic import behaviors, something like the following:

```ts
async function loadTSConfig(root: string): TSConfig | undefined {
  const tsconfigPath = path.join(root, 'tsconfig.json')
  if (fs.existsSync(tsconfigPath)) {
    const { parseConfigFileTextToJson } = await import('typescript')
```

File: src/ts-node.ts [hunk 3]
```diff
@@ -1,16 +1,21 @@
 import * as fs from 'fs'
 import * as path from 'path'
 import * as TSNode from 'ts-node'
-import {parseConfigFileTextToJson} from 'typescript'
 
 import Debug from './debug'
+const debug = Debug()
+
+let typescript: typeof import('typescript')
```
[the remark this answers is not in the document]
Comment (indexzero) [reply src/ts-node.ts]: You sir, are thinking like JavaScript! This was my original implementation, but TypeScript got very cranky with me since the type for `let typescript` could not be inferred automagically.

[the remark this answers is not in the document]
Comment (blackdynamo) [reply src/ts-node.ts]: Thank you for the explanation! 

I am still not Typescript convinced, and I come from C# and Java background. I just haven't come across issues that I can see typescript solving that proper testing, prs, lint, and other process can't solve. I also can't see typescript solving the problems of those other areas, so they would still be required.

[the remark this answers is not in the document]
Comment (indexzero) [reply src/ts-node.ts]: I am a JavaScript person as well, but hey – open source means exploring new things 🤷‍♂️

[the remark this answers is not in the document]
Comment (jdxcode) [reply src/ts-node.ts]: I'm not entirely sure myself why this works (but it does, the type is correct here and not a promise).

I think that `import()` behaves differently in the value position vs the type position.

value position (promise):

```typescript
async function () {
  let typescript = await import('typescript')
}
```

type position:

```typescript
async function () {
  let typescript: typeof import('typescript') = await import('typescript')
}
```

dynamic imports are admittedly not very clean in typescript and this is weird behavior in any case

[the remark this answers is not in the document]
Comment (jdxcode) [reply src/ts-node.ts]: screen shot 2019-01-31 at 10 45 33

[the remark this answers is not in the document]
Comment (blackdynamo) [reply src/ts-node.ts]: So what's the type if typescript isn't installed and this code runs?

```
let typescript: typeof import('typescript')```

[the remark this answers is not in the document]
Comment (jdxcode) [reply src/ts-node.ts]: there are no types when the code is running, typescript types are only used at compile-time

[the remark this answers is not in the document]
Comment (blackdynamo) [reply src/ts-node.ts]: So I guess it's working because since typescript has to run to compile this source code, typescript is available at compile time in this scenario. So it just works. I wonder if this would work if the dependency was something other than typescript.

PS. Sorry for the chatty conversation, I fully respect your inboxes!

[the remark this answers is not in the document]
Comment (trevor-scheer) [reply src/ts-node.ts]: @blackdynamo - I agree with you. While it works, I think it's technically incorrect that `typescript` is being required at runtime, but not required as a dependency.

https://github.com/oclif/config/pull/72#discussion_r252495685

[the remark this answers is not in the document]
Comment (indexzero) [reply src/ts-node.ts]: Okay, storytime. Back in the day there was a dream – a dream called [`optionalDependencies`](https://docs.npmjs.com/files/package.json#optionaldependencies). 

The current behavior of `optionalDependencies` is just a tiny fraction of what was discussed when it was being planned ... at least 6 years ago.

Behavior that would have covered this scenario: **opt-in dependencies**. What I mean by that is `typescript` is not _actually_ a run-time dependency. It is a "nice to have" that only attempts to parse `tsconfig.json` file when present. 

There are a lot of grey areas like this in production scenarios for package management. Lazy require is a well known technique to handle them which imho is appropriate here.

[the remark this answers is not in the document]
Comment (trevor-scheer) [reply src/ts-node.ts]: TIL! Thanks for the further explanation 👍
