### ISSUE TITLE
v1.12.2 causes cli issues

### ISSUE THREAD

**Issue by blackdynamo** [oclif/config#71]
I am not using the typescript option. Things worked fine in v1.12.0.

```
> ./bin/run

module.js:550
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xxx/sourcecode/service/node_modules/@oclif/config/lib/ts-node.js:5:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

**Comment by indexzero** [comment]
+1 it appears that this was introduced in https://github.com/oclif/config/pull/70. Hoping to find someone in [the Gitter chat](https://gitter.im/oclif/oclif) to help triage.

**Comment by evans** [comment]
In case it helps, we're using typescript and see the error as well

![screen shot 2019-01-30 at 4 05 36 pm](https://user-images.githubusercontent.com/5565407/52021211-0c8ab280-24a9-11e9-97ac-39c7b86e7c08.png)

**Comment by cwhatley** [comment]
I reported this earlier here: https://github.com/oclif/oclif/issues/204 and will close it.

**Comment by indexzero** [comment]
Fixed by #72.
